/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/book': {
    post: operations['addBookUsingPOST'];
  };
  '/book/list': {
    get: operations['queryBookListUsingGET'];
  };
  '/book/update': {
    post: operations['updateUsingPOST'];
  };
  '/book/{ids}': {
    delete: operations['deleteBookUsingDELETE'];
  };
  '/index': {
    get: operations['indexUsingGET'];
    put: operations['indexUsingPUT'];
    post: operations['indexUsingPOST'];
    delete: operations['indexUsingDELETE'];
    options: operations['indexUsingOPTIONS'];
    head: operations['indexUsingHEAD'];
    patch: operations['indexUsingPATCH'];
  };
  '/learn': {
    get: operations['learnUsingGET'];
    put: operations['learnUsingPUT'];
    post: operations['learnUsingPOST'];
    delete: operations['learnUsingDELETE'];
    options: operations['learnUsingOPTIONS'];
    head: operations['learnUsingHEAD'];
    patch: operations['learnUsingPATCH'];
  };
  '/learn/add': {
    post: operations['addLearnUsingPOST'];
  };
  '/learn/delete': {
    post: operations['deleteUserUsingPOST'];
  };
  '/learn/queryLeanList': {
    post: operations['queryLearnListUsingPOST'];
  };
  '/learn/update': {
    post: operations['updateLearnUsingPOST'];
  };
  '/login': {
    /** 通过用户名和密码登录 */
    post: operations['loginUsingPOST'];
  };
  '/main': {
    get: operations['mainUsingGET'];
    put: operations['mainUsingPUT'];
    post: operations['mainUsingPOST'];
    delete: operations['mainUsingDELETE'];
    options: operations['mainUsingOPTIONS'];
    head: operations['mainUsingHEAD'];
    patch: operations['mainUsingPATCH'];
  };
  '/register': {
    post: operations['registerUsingPOST'];
  };
  '/user/add': {
    post: operations['userAddUsingPOST'];
  };
  '/user/delete': {
    post: operations['userDeleteUsingPOST'];
  };
  '/user/info': {
    /** 根据token获取用户信息 */
    get: operations['userInfoByTokenUsingGET'];
  };
  '/user/infoById': {
    /** 根据id获取用户信息 */
    get: operations['userInfoByIdUsingGET'];
  };
  '/user/list': {
    get: operations['userListUsingGET'];
  };
  '/user/update': {
    post: operations['userUpdateUsingPOST'];
  };
}

export interface definitions {
  /** LoginDto */
  LoginDto: {
    /**
     * @description 密码
     * @example 123456
     */
    password: string;
    /**
     * @description 用户名
     * @example admin
     */
    username: string;
  };
  /**
   * OkResponseDto
   * @description 成功信息
   */
  OkResponseDto: { [key: string]: unknown };
  /** Page«UserListResponseDto» */
  'Page«UserListResponseDto»': {
    list?: definitions['UserListResponseDto'][];
    /** Format: int32 */
    total?: number | null;
  };
  /** RegisterDto */
  RegisterDto: {
    /**
     * @description 昵称
     * @example xxx@163.com
     */
    email: string;
    /**
     * @description 昵称
     * @example 明日香
     */
    nickName?: string;
    /**
     * @description 密码
     * @example 123456
     */
    password: string;
    /**
     * @description 手机号
     * @example xxx
     */
    phone: string;
    /**
     * @description 用户名
     * @example admin
     */
    username: string;
  };
  /** Result«OkResponseDto» */
  'Result«OkResponseDto»': {
    /** @enum {string} */
    code?: '200' | '401' | '400' | '501' | '500';
    data: definitions['OkResponseDto'];
    message?: string;
  };
  /** Result«Page«UserListResponseDto»» */
  'Result«Page«UserListResponseDto»»': {
    /** @enum {string} */
    code?: '200' | '401' | '400' | '501' | '500';
    data: definitions['Page«UserListResponseDto»'];
    message?: string;
  };
  /** Result«UserInfoResponseDto» */
  'Result«UserInfoResponseDto»': {
    /** @enum {string} */
    code?: '200' | '401' | '400' | '501' | '500';
    data: definitions['UserInfoResponseDto'];
    message?: string;
  };
  /** Result«string» */
  'Result«string»': {
    /** @enum {string} */
    code?: '200' | '401' | '400' | '501' | '500';
    data: string;
    message?: string;
  };
  /** UserAddDto */
  UserAddDto: {
    /**
     * @description 邮箱
     * @example xxx@163.com
     */
    email: string;
    /**
     * @description 昵称
     * @example 明日香
     */
    nickName?: string;
    /**
     * @description 手机号
     * @example xxx
     */
    phone: string;
  };
  /** UserDeleteDto */
  UserDeleteDto: {
    /**
     * @description ids
     * @example 1
     */
    ids?: string;
  };
  /**
   * UserInfoResponseDto
   * @description 用户信息
   */
  UserInfoResponseDto: {
    /**
     * Format: date-time
     * @description 创建时间
     */
    createdAt?: string;
    /** @description 邮箱 */
    email?: string;
    /**
     * Format: int64
     * @description 用户id
     */
    id?: string;
    /** @description 昵称 */
    nickName?: string;
    /** @description 手机 */
    phone?: string;
    /**
     * Format: date-time
     * @description 修改时间
     */
    updatedAt?: string;
  };
  /**
   * UserListResponseDto
   * @description 用户信息
   */
  UserListResponseDto: {
    /**
     * Format: date-time
     * @description 创建时间
     */
    createdAt?: string;
    /** @description 邮箱 */
    email?: string;
    /**
     * Format: int64
     * @description 用户id
     */
    id?: string;
    /** @description 昵称 */
    nickName?: string;
    /** @description 手机 */
    phone?: string;
    /**
     * Format: date-time
     * @description 修改时间
     */
    updatedAt?: string;
  };
  /** UserUpdateDto */
  UserUpdateDto: {
    /**
     * @description 邮箱
     * @example xxx@163.com
     */
    email?: string;
    /**
     * Format: int64
     * @description id
     * @example 1
     */
    id: string;
    /**
     * @description 昵称
     * @example 明日香
     */
    nickName?: string;
    /**
     * @description 手机号
     * @example xxx
     */
    phone: string;
  };
}

export interface operations {
  addBookUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  queryBookListUsingGET: {
    parameters: {
      query: {
        /** currentPage */
        currentPage?: string;
        /** pageSize */
        pageSize?: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  updateUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  deleteBookUsingDELETE: {
    parameters: {
      path: {
        /** ids */
        ids: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  indexUsingGET: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  indexUsingPUT: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  indexUsingPOST: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  indexUsingDELETE: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  indexUsingOPTIONS: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  indexUsingHEAD: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  indexUsingPATCH: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  learnUsingGET: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  learnUsingPUT: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  learnUsingPOST: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  learnUsingDELETE: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  learnUsingOPTIONS: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  learnUsingHEAD: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  learnUsingPATCH: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  addLearnUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  deleteUserUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  queryLearnListUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  updateLearnUsingPOST: {
    responses: {
      /** OK */
      200: unknown;
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  /** 通过用户名和密码登录 */
  loginUsingPOST: {
    parameters: {
      body: {
        /** 登录请求参数 */
        loginDto: definitions['LoginDto'];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«string»'];
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  mainUsingGET: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  mainUsingPUT: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  mainUsingPOST: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  mainUsingDELETE: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  mainUsingOPTIONS: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  mainUsingHEAD: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  mainUsingPATCH: {
    responses: {
      /** OK */
      200: {
        schema: string;
      };
      /** No Content */
      204: never;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  registerUsingPOST: {
    parameters: {
      body: {
        /** 注册请求参数 */
        responseDto: definitions['RegisterDto'];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«UserInfoResponseDto»'];
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  userAddUsingPOST: {
    parameters: {
      body: {
        /** 新增用户 */
        userAddDto: definitions['UserAddDto'];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«UserInfoResponseDto»'];
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  userDeleteUsingPOST: {
    parameters: {
      body: {
        /** 删除用户 */
        userDeleteDto: definitions['UserDeleteDto'];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«OkResponseDto»'];
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  /** 根据token获取用户信息 */
  userInfoByTokenUsingGET: {
    parameters: {
      header: {
        /** Authorization */
        Authorization: string;
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«UserInfoResponseDto»'];
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  /** 根据id获取用户信息 */
  userInfoByIdUsingGET: {
    parameters: {
      query: {
        /** 用户ID */
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«UserInfoResponseDto»'];
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  userListUsingGET: {
    parameters: {
      query: {
        /** 页码 */
        currentPage?: number | null;
        /** 关键字 */
        keyWord?: string;
        /** 分页大小 */
        pageSize?: number | null;
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«Page«UserListResponseDto»»'];
      };
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
  userUpdateUsingPOST: {
    parameters: {
      body: {
        /** 编辑用户 */
        userUpdateDto: definitions['UserUpdateDto'];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions['Result«UserInfoResponseDto»'];
      };
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
      /** Not Found */
      404: unknown;
    };
  };
}

export interface external {}
