interface PathToComponet {
  [propName: string]: Function
}

const pathToComponet: PathToComponet = {
  '/console/workshop': () => import('@/views/console/workshop/WorkshopList.vue'),
  '/console/device': () => import('@/views/console/device/DeviceList.vue'),
  '/console/mold': () => import('@/views/console/mold/MoldList.vue'),
  '/console/team': () => import('@/views/console/team/TeamList.vue'),
  '/console/list': () => import('@/views/console/team/TeamPersonList.vue'),
  '/BusinessRecords/person': () => import('@/views/BusinessRecords/person/PersonList.vue'),
  '/BusinessRecords/invlist': () => import('@/views/BusinessRecords/invlist/InvList.vue'),
  '/BusinessRecords/cuslist': () => import('@/views/BusinessRecords/cuslist/CusList.vue'),
  '/BusinessRecords/whlist': () => import('@/views/BusinessRecords/whlist/WhList.vue'),
  '/BusinessRecords/vendors': () => import('@/views/BusinessRecords/vendors/VendorsList.vue'),
  '/BusinessRecords/oplist': () => import('@/views/BusinessRecords/oplist/OpList.vue'),
  '/BusinessRecords/prlist': () => import('@/views/BusinessRecords/prlist/PrList.vue'),
  '/BusinessRecords/bill': () => import('@/views/BusinessRecords/bill/BillList.vue'),
  '/System/SysIpWhite': () => import('@/views/System/SysIpWhite/SysIpWhite.vue'),
  '/System/pdaauthlist': () => import('@/views/System/pdaauthList/pdaauthList.vue'),
  '/System/role': () => import('@/views/System/roleList/roleList.vue'),
  '/System/apply': () => import('@/views/System/apply/applyAms.vue'),
  '/System/user': () => import('@/views/System/user/userControl.vue'),
  '/System/menu': () => import('@/views/System/menu/menuManager.vue'),
  '/System/authority': () => import('@/views/System/authority/authorityManagement.vue'),
  '/System/dictionariesVal': () => import('@/views/System/dictionaries/dictionaryManagement.vue'),
  '/business/momPlanIssue': () => import('@/views/business/momPlanIssue/MomPlanIssueList.vue'),
  '/business/MomPlanIssuePropectList': () => import('@/views/business/momPlanIssue/MomPlanIssuePropectList.vue'),
  '/BarCode/braCodeData': () => import('@/views/barCode/barCodeSource/barCodeSource.vue'),
  '/BarCode/setBarCodeList': () => import('@/views/barCode/setBarCodeList/SetBarCodeList.vue'),
  '/BarCode/setBarCode': () => import('@/views/barCode/setBarCode/SetBarCode.vue'),
  '/statement/reportMolds': () => import('@/views/statement/reportMolds/ReportMolds.vue'),
  '/statement/reportDev': () => import('@/views/statement/reportDev/ReportDev.vue'),
  '/statement/moopreport': () => import('@/views/statement/moopReport/MoopReport.vue'),
  '/statement/taskpage': () => import('@/views/statement/taskPage/TaskPage.vue'),
  '/statement/productionPlan': () => import('@/views/statement/productionPlan/ProductionPlan.vue'),
  '/business/momshiftlist': () => import('@/views/business/momShiftList/MomShiftList.vue'),
  '/business/momshift': () => import('@/views/business/momShiftList/momShift.vue'),
  '/business/mobill': () => import('@/views/business/mobill/mobillWorkTicket.vue'),
  '/business/mobillList': () => import('@/views/business/mobill/mobillWorkTicketList.vue'),
  '/business/MomPlanIssueAddForm': () => import('@/views/business/momPlanIssue/MomPlanIssueAddForm.vue'),
  '/business/momPlanIssueInfoAdd': () => import('@/views/business/momPlanIssue/MomPlanIssueAddTb.vue'),
  '/business/momshiftAdd': () => import('@/views/business/momShiftList/momShift.vue'),
  '/business/momshiftEdit': () => import('@/views/business/momShiftList/momShift.vue'),
  '/APS/MomAPS': () => import('@/views/APS/MomAPS/MomAPS.vue'),
  '/APS/MomAPSList': () => import('@/views/APS/MomAPS/MomAPSList.vue'),
  '/checks/checksTask': () => import('@/views/checks/checksTask/ChecksTaskList.vue'),
  '/checks/checksTaskInfo': () => import('@/views/checks/checksDetail/checksTaskInfo.vue'),
  '/checks/checksSumList': () => import('@/views/checks/checksSumList/checksSumList.vue'),
  '/checks/checksSum': () => import('@/views/checks/checksSum/checksSum.vue'),
  '/checks/checksSumAdd': () => import('@/views/checks/checksSum/checksSum.vue'),
  '/checks/checksSumEdit': () => import('@/views/checks/checksSum/checksSum.vue'),
  '/console/teamShiftCalendar': () => import('@/views/console/teamShiftCalendar/TeamShifteCalendar.vue'),
  '/console/teamShiftCalendarList': () => import('@/views/console/teamShiftCalendar/TeamShifteCalendarList.vue'),
  '/console/teamShift': () => import('@/views/console/teamShift/TeamShiftList.vue'),
  '/business/leaveDoc': () => import('@/views/business/leaveDoc/LeaveDocList.vue'),
  '/business/temTransferDoc': () => import('@/views/business/temTransferDoc/TemTransferDocList.vue'),
  '/business/CapacityCompare': () => import('@/views/business/capacityCompare/CapacityCompare.vue'),
  '/business/CapacityCompareAdd': () => import('@/views/business/capacityCompare/CapacityCompare.vue'),
  '/business/CapacityCompareEdit': () => import('@/views/business/capacityCompare/CapacityCompare.vue'),
  '/business/CapacityCompareList': () => import('@/views/business/capacityCompare/CapacityCompareList.vue'),
  '/business/inspectionMethod': () => import('@/views/business/inspectionMethod/inspectionMethodList.vue'),

  '/console/WDeviceList': () => import('@/views/console/worksheetList/WorksheetList.vue'),
  '/console/WMoldList': () => import('@/views/console/worksheetList/WorksheetList.vue'),
  // 申请单
  '/console/RADevice': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RADeviceAdd': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RADeviceEdit': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RADeviceList': () => import('@/views/console/worksheetList/RepairApplicationList.vue'),
  '/console/MADevice': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MADeviceAdd': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MADeviceEdit': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MADeviceList': () => import('@/views/console/worksheetList/RepairApplicationList.vue'),
  '/console/RAMold': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RAMoldAdd': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RAMoldEdit': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/RAMoldList': () => import('@/views/console/worksheetList/RepairApplicationList.vue'),
  '/console/MAMold': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MAMoldAdd': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MAMoldEdit': () => import('@/views/console/worksheetList/RepairApplication.vue'),
  '/console/MAMoldList': () => import('@/views/console/worksheetList/RepairApplicationList.vue'),
  // 工单
  '/console/RODevice': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/RODeviceAdd': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/RODeviceEdit': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/RODeviceList': () => import('@/views/console/repairMaintain/RepairMaintainOrderList.vue'),
  '/console/MODevice': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MODeviceAdd': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MODeviceEdit': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MODeviceList': () => import('@/views/console/repairMaintain/RepairMaintainOrderList.vue'),
  '/console/ROMold': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/ROMoldAdd': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/ROMoldEdit': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/ROMoldList': () => import('@/views/console/repairMaintain/RepairMaintainOrderList.vue'),
  '/console/MOMold': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MOMoldAdd': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MOMoldEdit': () => import('@/views/console/repairMaintain/RepairMaintainOrders.vue'),
  '/console/MOMoldList': () => import('@/views/console/repairMaintain/RepairMaintainOrderList.vue'),
  '/console/worksheet': () => import('@/views/console/worksheetList/WorksheetAdd.vue'),
  '/console/worksheetAdd': () => import('@/views/console/worksheetList/WorksheetAdd.vue'),
  '/console/worksheetEdit': () => import('@/views/console/worksheetList/WorksheetAdd.vue'),
  '/facility/faultClass': () => import('@/views/facility/faultClass/FaultClass.vue'),
  // 计划与通知
  '/console/RSDevice': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSDeviceAdd': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSDeviceEdit': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSDeviceList': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesList.vue'),
  '/console/MSDevice': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSDeviceAdd': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSDeviceEdit': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSDeviceList': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesList.vue'),
  '/console/RSMold': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSMoldAdd': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSMoldEdit': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/RSMoldList': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesList.vue'),
  '/console/MSMold': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSMoldAdd': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSMoldEdit': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesAdd.vue'),
  '/console/MSMoldList': () => import('@/views/console/maintenanceNoticeList/MaintenanceSchedulesList.vue'),
  '/console/NDeviceList': () => import('@/views/console/maintenanceNoticeList/MaintenanceNoticeList.vue'),
  '/console/NMoldList': () => import('@/views/console/maintenanceNoticeList/MaintenanceNoticeList.vue'),
  // 巡检
  '/console/IPQCDispatch': () => import('@/views/console/IPQCDispatch/IPQCDispatch.vue'),
  '/console/IPQCTask': () => import('@/views/console/IPQCTask/IPQCTask.vue'),
  '/console/pollingList': () => import('@/views/console/pollingList/PollingList.vue'),
  // 系统配置
  '/System/config': () => import('@/views/System/config/ConfigList.vue')
}

export default pathToComponet
