interface PackageConfigKeyToNameType {
  [key: string]: string
}

// 缓存值映射名称
const packageConfigKeyToName: PackageConfigKeyToNameType = {
  skinConfig: '皮肤设置',
  tableConfigDeviceListTable: '设备档案表格',
  tablePageDeviceListTable: '设备档案分页',
  tableConfigMomAPSListTable: '可视化排程列表表格',
  tablePageMomAPSListTable: '可视化排程列表分页',
  tableConfigBillListTable: '物料清单表格',
  tablePageBillListTable: '物料清单分页',
  tableConfigBillChildrenListTable: '物料清单明细表格',
  tablePageBillChildrenListTable: '物料清单明细分页',
  tableConfigCusListTable: '客户档案表格',
  tablePageCusListTable: '客户档案分页',
  tableConfigInvListTable: '存货档案表格',
  tablePageInvListTable: '存货档案分页',
  tableConfigOpListTable: '工序档案表格',
  tablePageOpListTable: '工序档案分页',
  tableConfigPersonListTable: '人员档案表格',
  tablePagePersonListTable: '人员档案分页',
  tableConfigStocksListTable: '工艺路线档案表格',
  tablePageStocksListTable: '工艺路线档案分页',
  tableConfigPrListTable: '工艺路线档案明细表格',
  tablePagePrListTable: '工艺路线档案明细分页',
  tableConfigVendorsListTable: '供应商档案表格',
  tablePageVendorsListTable: '供应商档案分页',
  tableConfigWhListTable: '仓库档案表格',
  tablePageWhListTable: '仓库档案分页',
  tableConfigSysIpWhite: 'ip白名单管理表格',
  tablePageSysIpWhite: 'ip白名单管理分页',
  tableConfigApplyAms: '应用管理表格',
  tablePageApplyAms: '应用管理分页',
  tableConfigRoleTab: '权限管理表格(角色人员)',
  tablePageRoleTab: '权限管理表格(角色人分页',
  tableConfigPeopleRightTab: '权限管理表格(角色权限)',
  tablePagePeopleRightTab: '权限管理表格(角色权分页',
  tableConfigDictionariesClassify: '字典分类表格',
  tablePageDictionariesClassify: '字典分类分页',
  tableConfigRoleList: '角色管理表格',
  tablePageRoleList: '角色管理分页',
  tableConfigMnuManager: '菜单管理表格',
  tablePageMnuManager: '菜单管理分页',
  tableConfigPdaauthList: 'PDA设备许可表格',
  tablePagePdaauthList: 'PDA设备许可分页',
  tableConfigDictionaryManagementList: '字典管理表格',
  tablePageDictionaryManagementList: '字典管理分页',
  tableConfigUserControl: '用户管理表格',
  tablePageUserControl: '用户管理分页',
  tableConfigBarCode: '条码数据源表格',
  tablePageBarCode: '条码数据源分页',
  tableConfigSetBarCodeFlowCardTable: '条码生成表格(流转卡)',
  tablePageSetBarCodeFlowCardTable: '条码生成表格(流转分页',
  tableConfigSetBarCodeInWareTable: '条码生成表格(产成品入库)',
  tablePageSetBarCodeInWareTable: '条码生成表格(产成品入分页',
  tableConfigSetBarCodeInventoryTable: '条码生成表格(存货)',
  tablePageSetBarCodeInventoryTable: '条码生成表格(存分页',
  tableConfigSetBarCodePositionTable: '条码生成表格(货位)',
  tablePageSetBarCodePositionTable: '条码生成表格(货分页',
  tableConfigSetBarCodeMoldTable: '条码生成表格(模具)',
  tablePageSetBarCodeMoldTable: '条码生成表格(模分页',
  tableConfigSetBarCodeDEVICETable: '条码生成表格(设备)',
  tablePageSetBarCodeDEVICETable: '条码生成表格(设分页',
  tableConfigSetBarCodeOpFlowCardTable: '条码生成表格(工序流转卡)',
  tablePageSetBarCodeOpFlowCardTable: '条码生成表格(工序流转分页',
  tableConfigSetBarCodePUARRTable: '条码生成表格(采购到货)',
  tablePageSetBarCodePUARRTable: '条码生成表格(采购到货)',
  tableConfigSetBarCodeListTable: '条码打印表格',
  tablePageSetBarCodeListTable: '条码打印分页',
  tableConfigCapacityCompareTable: '产品工序设备产能对照表格(产能)',
  tablePageCapacityCompareTable: '产品工序设备产能对照表格(产分页',
  tableConfigCapacityTable: '产品工序设备产能对照表格(工序)',
  tablePageCapacityTable: '产品工序设备产能对照表格(工分页',
  tableConfigMomShiftListTable: '派工报表表格',
  tablePageMomShiftListTable: '派工报表分页',
  tableConfigLeaveDocListTable: '请假单表格',
  tablePageLeaveDocListTable: '请假单分页',
  tableConfigWorktickListTable: '报工单表格',
  tablePageWorktickListTable: '报工单分页',
  tableConfigworkTicketListTable: '报工单报表表格',
  tablePageworkTicketListTable: '报工单报表分页',
  tableConfigMomPlanIssueAddTbTable: 'MRP计划下达新增MRP计划表格',
  tablePageMomPlanIssueAddTbTable: 'MRP计划下达新增MRP计划分页',
  tableConfigMomPlanIssueListTable: '计划下达表格',
  tablePageMomPlanIssueListTable: '计划下达分页',
  tableConfigMomPlanIssuePropectItemList: '子件领料详情表格',
  tablePageMomPlanIssuePropectItemList: '子件领料详情分页',
  tableConfigMomPlanIssuePropectList: '计划下达齐料展望表格',
  tablePageMomPlanIssuePropectList: '计划下达齐料展望分页',
  tableConfigMomAddTable: '新增生产派工单表格',
  tablePageMomAddTable: '新增生产派工单分页',
  tableConfigMomSchedulingAddTable: '排产单可派工表格',
  tablePageMomSchedulingAddTable: '排产单可派工分页',
  tableConfigCapacityCompareListTable: '产品工序设备产能对照表表格',
  tablePageCapacityCompareListTable: '产品工序设备产能对照表分页',
  // tableConfigMomShiftTable: '生产派工单表格',
  // tablePageMomShiftTable: '生产派工单分页',
  tableConfigTemTransferDocListTable: '借调单表格',
  tablePageTemTransferDocListTable: '借调单分页',
  tableConfigChecksTaskTable: '盘点任务表格',
  tablePageChecksTaskTable: '盘点任务分页',
  tableConfigChecksSumTable: '盘点汇总单表格',
  tablePageChecksSumTable: '盘点汇总单分页',
  tableConfigChecksSumAddModelTable: '待汇总记录表格',
  tablePageChecksSumAddModelTable: '待汇总记录分页',
  tableConfigChecksTaskListTable: '盘点汇总列表表格',
  tablePageChecksTaskListTable: '盘点汇总列表分页',
  tableConfigChecksTaskInfoTable: '盘点明细表格',
  tablePageChecksTaskInfoTable: '盘点明细分页',
  tableConfigMaintenanceNoticeListTable: '设备/模具通知单列表表格',
  tablePageMaintenanceNoticeListTable: '设备/模具通知单列表分页',
  tableConfigMaintenanceSchedulesListTable: '设备/模具维修/保养计划列表表格',
  tablePageMaintenanceSchedulesListTable: '设备/模具维修/保养计划列表分页',
  tableConfigMoldListTable: '模具档案表格',
  tablePageMoldListTable: '模具档案分页',
  tableConfigRepairMaintainOrderListTable: '设备/模具维修/保养工单列表表格',
  tablePageRepairMaintainOrderListTable: '设备/模具维修/保养工单列表分页',
  tableConfigTeamPresonList: '班组人员维护表格',
  tablePageTeamPresonList: '班组人员维护分页',
  tableConfigTeamListTable: '班组档案表格',
  tablePageTeamListTable: '班组档案分页',
  tableConfigTeamPersonList: '班组人员对照表格(班组)',
  tablePageTeamPersonList: '班组人员对照表格(班分页',
  tableConfigPresonTeamList: '班组人员对照表格(人员)',
  tablePagePresonTeamList: '班组人员对照表格(人分页',
  tableConfigTeamShiftListTable: '班次档案表格',
  tablePageTeamShiftListTable: '班次档案分页',
  tableConfigTeamShifteCalendarListTable: '班次日历列表表格',
  tablePageTeamShifteCalendarListTable: '班次日历列表分页',
  tableConfigRepairMaintainListTable: '设备/模具维修/保养申请列表表格',
  tablePageRepairMaintainListTable: '设备/模具维修/保养申请列表分页',
  tableConfigWorksheetListTable: '设备/模具作业单列表表格',
  tablePageWorksheetListTable: '设备/模具作业单列表分页',
  tableConfigWorkshopListTable: '车间档案表格',
  tablePageWorkshopListTable: '车间档案分页',
  tableConfigFaultclass: '故障分类表格',
  tablePageFaultclass: '故障分类分页',
  tableConfigMoopReportTable: '生产工序在制表表格',
  tablePageMoopReportTable: '生产工序在制表分页',
  tableConfigProductionPlanTable: '生产计划一览表表格',
  tablePageProductionPlanTable: '生产计划一览表分页',
  tableConfigReportDevTable: '设备状态一览表表格',
  tablePageReportDevTable: '设备状态一览表分页',
  tableConfigReportMoldsTable: '模具状态一览表表格',
  tablePageReportMoldsTable: '模具状态一览表分页',
  tableConfigTaskPageTable: '派工任务一览表表格',
  tablePageTaskPageTable: '派工任务一览分页格',
  tableConfigIPQCTaskListTable: '调度任务列表表格 ',
  tablePageIPQCTaskListTable: '调度任务列表分页',
  tableConfigIPQCDispatchListTable: '巡检调度列表表格 ',
  tablePageIPQCDispatchListTable: '巡检调度列表分页',
  tableConfigPollingListTable: '巡检流转卡列表表格 ',
  tablePagePollingListTable: '巡检流转卡列表分页',
  tableConfiginspectionMethodListTable: '检验任务列表表格 ',
  tablePageinspectionMethodListTable: '检验任务列表分页',
  'billAdd-Left': '物料清单新增-左',
  // 'billAdd-Right': '物料清单新增-右',
  'bill-Left': '物料清单-左',
  // 'bill-Right': '物料清单-右',
  'pr-Left': '工艺路线-左',
  // 'pr-Right': '工艺路线-右',
  'team-Left': '人员班组-左',
  // 'team-Right': '人员班组-右',
  'reconciliation-Left': '产能对照-左',
  // 'reconciliation-Right': '产能对照-右',
  'authority-Left': '角色-左',
  // 'authority-Right': '角色-右',
  tableConfigWorktickListInfoTable: '报工单子表格',
  tableConfigChecksSumInfoTable: '盘点汇总单子表格',
  tableConfigMoopReportInfoTable: '派工任务列表子表格'
}

export default packageConfigKeyToName
